# prepare (need venv if default python is python2)

# pip install mkdocs mkdocs-bootswatch pymdown-extensions
# pip install mkdocs-material mkdocs-rss-plugin python-markdown-math
# pip install mkdocs-encryptcontent-plugin

# Personal info (replace cuzperf to username, mkdocs to repo name)

site_name: mkdocs template
site_author: 'cuzperf'
site_url: 'https://cuzperf.github.io/mkdocs'

repo_name: cuzperf/mkdocs
repo_url: https://github.com/cuzperf/mkdocs

copyright: Copyright © 2022 cuzperf

# Contents
nav:
  - 主页:
    - 示例: index.md
  - 关于: about.md

theme:
  name: material
  language: zh
  custom_dir: docs/theme
  highlightjs: true
  icon:
    repo: fontawesome/brands/git-alt
  logo: img/favicon.ico
  favicon: img/cuzperf.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: deep purple
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cuzperf/mkdocs
    - icon: fontawesome/solid/rss
      link: feed_rss_updated.xml

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - mdx_math:
      enable_dollar_delimiter: True
  # - pymdownx.arithmatex
  # - pymdownx.arithmatex:
      # generic: true
  - pymdownx.caret
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
# mathjax2（mathjax3 有 bug）:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css

plugins:
  - search
  - rss
